env:
  global:
    secure: mpQ+fjPeOz2PP4YUEoPQLePho2EC0snBjhz1Frv16qWqY4Bqu5wUGvWcs5Kwjw5oLPA0hCgZ5qNFmvx1CuFrZTqhtnbhUjfcu/h8VWnlzyoQnFrs5D5cIWDHReglPKu3EDNcpVCLDyBsTWlbk0dGNs/da6PNKQAQsXujXpsXaSjz97FlIQr57PAXPssRHJYhTAu42eKXD2VvIOvgOajhgeES2BX91ifTpUoqw3CSY+I7j3cE6lykpp2EWxq6kCQ7NZrep183ffW4pO29yYUTn4ylVxjBsEsMJ3m+E7c7M+5bdTWJFY8HjD4OMQqpmHsYcKTbSHOU0SVRorgo8q8G+t7yvhnyDO3vPP3rQuzngOu84b/jGjJRjEx7b7ogIXg2XIjKetEDLQvA0S/MQbGydXQYKnMKY20H/4Q96zg5VmO7mKiRlUID/IuptxxJE87RmTSZRyuRrCBxRoWFBSwGRXsk0NEmI75eFHtaeCrGdJDnHTiA2w/IoqlFZFeICbXn+db2nYqNc/tGNV8ZbJPzdrRGp70nvQj4yOVRPJkrM1MTODfuk3N5bQvy4yTFP6AKrQWmgWDS3sv0K204K8C1uTbWHCuWA5294lY/eXrHTqv2qB4LSJwsd2o3IzT13XPL8cWvO3Pu6buXZ+TI3pWZ1fssAE2WKr/GyBuZOPsYNp8=
sudo: false
os:
- osx
- linux
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
- npm install
- npm run vscode:prepublish
script:
- export CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/example
- npm test --silent
before_deploy:
- npm install -g vsce;
- vsce package;
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = osx"
