language: node_js
node_js:
  - 13
os:
- osx
# - linux
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
- npm install
- npm run vscode:prepublish
script:
- export CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/example
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CODE_VERSION=1.30.1;
  fi
- npm test --silent
before_deploy:
- npm install -g vsce;
- vsce package;
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN
  cleanup: false
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = osx"
    tags: true
