language: node_js
os:
- osx
- linux
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
- npm install
- npm run vscode:prepublish
script:
- export CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/example
- npm test
before_deploy:
- npm install -g vsce;
- vsce package;
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = osx"
    tags: true
